name: app_guias
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  file_picker: ^10.1.2
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  syncfusion_flutter_datepicker: ^29.1.37
  permission_handler: ^12.0.0
  device_info_plus: ^11.3.0
  open_file: ^3.5.10
  http_parser: ^4.1.2
  path: ^1.9.1
  shimmer: ^3.0.0
  share_plus: ^10.1.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# Configuración MSIX para generar el instalador de Windows
msix_config:
  display_name: App Guías
  publisher_display_name: Ebim
  identity_name: com.ebim.appguias
  msix_version: 1.0.0.0
  logo_path: assets/images/logo_manuelita.png